export const perks = [
    { name: "Aquanaut", category: "Movement", buffType: "Swimming Speed", debuffType: "Stamina Costs", img: "Aquanaut_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Controlled Breathing", category: "Stealth", buffType: "Fear Reduction", debuffType: "Stamina Regen", img: "Controlled_Breathing_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Easy Listening", category: "Survival", buffType: "Stamina Regen", debuffType: "Fear Resistance", img: "Easy_Listening_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Escape Artist", category: "Combat", buffType: "Grip Break", debuffType: "Total Stamina", img: "Escape_Artist_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Evasion", category: "Movement", buffType: "Dodge Speed", debuffType: "Damage Taken", img: "Evasion_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Firecracker", category: "Combat", buffType: "Stun Radius", debuffType: "Noise Generation", img: "Firecracker_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Friendship", category: "Social", buffType: "Attack Damage", debuffType: "Total Stamina", img: "Friendship_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Grease Monkey", category: "Repair", buffType: "Car Start Time", debuffType: "Engine Restart", img: "Grease_Monkey_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Grinder", category: "Utility", buffType: "XP Gain", debuffType: "Melee Damage", img: "Grinder_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Heavy Hitter", category: "Combat", buffType: "Stun Duration", debuffType: "Total Stamina", img: "Heavy_Hitter_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Heavy Mover", category: "Movement", buffType: "Barricade Speed", debuffType: "Total Stamina", img: "Heavy_Mover_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Heavy Sleeper", category: "Stealth", buffType: "Sense Avoidance", debuffType: "Fear Resistance", img: "Heavy_Sleeper_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Homebody", category: "Stealth", buffType: "Sense Avoidance", debuffType: "Total Stamina", img: "Homebody_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Hypochondriac", category: "Survival", buffType: "Medical Spray", debuffType: "Damage Taken", img: "Hypochondriac_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Ice Cold", category: "Survival", buffType: "Fear Reduction", debuffType: "Sprint Speed", img: "Ice_Cold_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Lead Foot", category: "Movement", buffType: "Car Top Speed", debuffType: "Vehicle Handling", img: "Lead_Foot_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Level Headed", category: "Stealth", buffType: "Sense Avoidance", debuffType: "Noise Generation", img: "Level_Headed_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Light Foot", category: "Stealth", buffType: "Noise Reduction", debuffType: "Fear Resistance", img: "Light_Foot_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Lone Wolf", category: "Social", buffType: "Attack Damage", debuffType: "Fear Resistance", img: "Lone_Wolf_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Low Profile", category: "Stealth", buffType: "Sense Avoidance", debuffType: "Sprint Speed", img: "Low_Profile_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Man At Arms", category: "Combat", buffType: "Weapon Durability", debuffType: "Stun Chance", img: "Man_At_Arms_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Marathon", category: "Movement", buffType: "Total Stamina", debuffType: "Sprint Speed", img: "Marathon_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Medic", category: "Survival", buffType: "Medical Spray Usage", debuffType: "Damage Taken", img: "Medic_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Motorboating", category: "Movement", buffType: "Boat Top Speed", debuffType: "Vehicle Handling", img: "Motorboating_Perk_Friday_the_13th_the_Game.webp" },
    { name: "My Dad's a Cop", category: "Utility", buffType: "Police Arrival Time", debuffType: "Objective Speed", img: "My_Dads_A_Cop_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Nerves of Steel", category: "Survival", buffType: "Fear Resistance", debuffType: "Stamina Regen", img: "Nerves_of_Steel_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Night Owl", category: "Survival", buffType: "Fear Reduction", debuffType: "Noise Generation", img: "Night_Owl_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Potent Herb", category: "Survival", buffType: "Healing Amount", debuffType: "Stamina Costs", img: "Potent_Herb_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Preparedness", category: "Utility", buffType: "Start with Map", debuffType: "Sprint Speed", img: "Preparedness_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Psychic", category: "Utility", buffType: "Start with Radio", debuffType: "Noise Generation", img: "Psychic_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Quiet Swimmer", category: "Stealth", buffType: "Sense Avoidance", debuffType: "Fear Resistance", img: "Quiet_Swimmer_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Restful", category: "Movement", buffType: "Stamina Regen", debuffType: "Sprint Speed", img: "Restful_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Scout", category: "Movement", buffType: "Trap Escape", debuffType: "Damage Taken", img: "Scout_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Slugger", category: "Combat", buffType: "Start with Bat", debuffType: "Attack Damage", img: "Slugger_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Sneaky", category: "Movement", buffType: "Window Speed", debuffType: "Damage Taken", img: "Sneaky_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Spatial Awareness", category: "Movement", buffType: "Stumble Chance", debuffType: "Noise Generation", img: "Spatial_Awareness_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Speed Demon", category: "Movement", buffType: "Vehicle Speed", debuffType: "Repair Speed", img: "Speed_Demon_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Sprint Burst", category: "Movement", buffType: "Sprint Speed", debuffType: "Total Stamina", img: "Sprint_Burst_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Sucker Punch", category: "Combat", buffType: "Stun Chance", debuffType: "Melee Damage", img: "Sucker_Punch_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Swift Sitter", category: "Movement", buffType: "Stamina Regen", debuffType: "Damage Taken", img: "Swift_Sitter_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Teamwork", category: "Social", buffType: "Fear Reduction", debuffType: "Attack Damage", img: "Teamwork_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Televised", category: "Utility", buffType: "Fear Resistance", debuffType: "Sprint Speed", img: "Televised_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Thick Skin", category: "Survival", buffType: "Damage Reduction", debuffType: "Stumble Chance", img: "Thick_Skin_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Thrasher", category: "Combat", buffType: "Axe Damage", debuffType: "Stun Chance", img: "Thrasher_Perk_Friday_the_13th_the_Game.webp" },
    { name: "Tinker", category: "Repair", buffType: "Repair Speed", debuffType: "Total Stamina", img: "Tinker_Perk_Friday_the_13th_the_Game.webp" }
];